### PR TITLE
Solution for GPCODECOVERAGE-47

### PR DESCRIPTION
**Pull request by noamt**
Grails controller field values are accessed by the post-test closure replacement procedures.
Noticeable during integration tests, controllers are injected with additional fields from classes such as CommonWebApi.
Some of these fields (such as the application context) cannot be accessed outside a request context, so they throw an exception during the replacement procedure.

Solution: added an iteration filter so that values are retrieved only for property descriptors of type Closure

### CODE REVIEW

**Comment by beckje01** [comment]
Looks good, I will create a snapshot version tomorrow we can test with.

**Comment by noamt** [comment]
Cheers

**Comment by noamt** [comment]
Any updates on this? Is there anything I can do to help?
I could really use this fix.

**Comment by beckje01** [comment]
Sorry I was trying to use bintray to get a snapshot version I was having issues. I will work on this tonight sorry for the delay.

**Comment by noamt** [comment]
Yeah, no snapshot versions are allowed on Bintray :)

**Comment by beckje01** [comment]
So that would be the problem not my configuration.

**Comment by beckje01** [comment]
I have a snapshot at https://repo-beckje01.rhcloud.com/artifactory/grails-plugins-snapshot/ You may need to hit the url first to make sure the artifactory is running. It is working for me if you don't mind giving the snapshot build a test I will get this deployed to the plugin portal if it is fixing your problem.

**Comment by noamt** [comment]
Looks good!

**Comment by cblume** [comment]
Hey, I might need some help to set it up correctly. How do I reference the Snapshot and where? (I'm quite new to Grails. I assume it's an easy fix?)

**Comment by noamt** [comment]
I'm pretty sure that you can do it by adding to your `BuildConfig.groovy` file's repositories section the line:

```
mavenRepo "https://repo-beckje01.rhcloud.com/artifactory/grails-plugins-snapshot"
```

And then just install normally.

**Comment by cblume** [comment]
That was definitely it. Thanks a lot!

**Pull request merged**
