### PR TITLE
Fix for Grails 2.3.2

### PR DESCRIPTION
**Pull request by armeris**
This patch fixes the problem I've had with Grails 2.3.2.
Don't know if it is a real issue but I make the pull request in case it is necessary.

### CODE REVIEW

**Comment by nwittstruck** [comment]
I'm having the same issue. Thank you for the fix! Would be great to have an updated version of the plugin published soon to be compatible with grails 2.3.2

**Comment by beckje01** [comment]
I can look at this tonight thanks for the Pull Request

**Comment by devnulled** [comment]
Any movement on this by chance @beckje01?  

I just ran into this bug as well and would prefer to not have to disable this stuff both in grails and Jenkins if there is a fixed build looming.  Thanks!

**Comment by nwittstruck** [comment]
Thank you! Could you also publish a snapshot release? Thank you very much for your efforts :)

**Comment by beckje01** [comment]
@nwittstruck I'm testing this locally and while there are no errors I'm not currently getting consistent reports of the coverage.

**Comment by nwittstruck** [comment]
Hmm, that's strange. Maybe it's related to the forked mode?

**Comment by beckje01** [comment]
Forked mode is off as well.

Jeff

**Comment by nwittstruck** [comment]
Hm, I'll take a look at this tomorrow. We might have to ask on the Grails user list, maybe one of the devs knows something.

**Comment by nwittstruck** [comment]
Hm, what results are you getting? The coverage seemed off for the first run, but now everything is looking fine for a couple of projects.

**Comment by beckje01** [comment]
No results at all what jdk are you using?

**Comment by nwittstruck** [comment]
java version "1.7.0_45", Mac OS X.

**Comment by beckje01** [comment]
Looks like I found the issue it was related to an external dependency that happened to be included in all my test projects.

**Comment by beckje01** [comment]
Thanks everyone for the help a new version is out today.

**Comment by nwittstruck** [comment]
Thank you very much!

**Comment by devnulled** [comment]
Thank you @beckje01, much appreciated!

**Comment by armeris** [comment]
Thx @beckje01!!

**Pull request merged**
