### PR TITLE
Changed the default Cobertura datafile to default to the project basedir...

### PR DESCRIPTION
**Pull request by shendrix**
..., and allow overriding using net.sourceforge.cobertura.datafile system property

### CODE REVIEW

**Comment by beckje01** [comment]
This looks great and would fix #32 correct? Would you mind also updating the README with some info on the override and add yourself as a contributor?

**Comment by shendrix** [comment]
I updated the README as you requested.  My change covers the configurable cobertura.ser location part of #32.

**Comment by beckje01** [comment]
Thanks for the help.

**Comment by shendrix** [comment]
No problem. When do you plan to release 2.0.3-3?

**Comment by beckje01** [comment]
No hard date I was going to test things a bit first but if you need it by a certain date let me know, I could do a release as quick as this afternoon.

**Comment by shendrix** [comment]
No not critical, I just don't like my dependency on my unofficial fork.

**Comment by shendrix** [comment]
Jeff, would you do a release when you get a chance? Thanks!

**Comment by beckje01** [comment]
@shendrix I'll work on that today

**Comment by beckje01** [comment]
@shendrix should be live in the portal

**Comment by shendrix** [comment]
@beckje01 Thanks Jeff!

**Pull request merged**
